### ISSUE TITLE
It looks awesome but I couldn't install it.

### ISSUE THREAD

**Issue by johan149** [marcelwestrahome/home-assistant-niu-component#1]
Awesome work, but hasnt able to make it work. I created a python_scripts folder inside the config root folder, inside I have placed the sensor.py and I added the yaml to the configuration.yaml, but it shows as invalid niu component is not a component. if you can write install instructions it would help a lot, I was able to get my token already dont know if that helps. Thank you, keep the great work!

**Comment by marcelwestrahome** [comment]
added some lines, will this help ? (you do not need python_scripts and\or token, component will handle this)
