### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by scapman** [marcelwestrahome/home-assistant-niu-component#12]
Dear.
Since HA version 2021.6.0 the component doesen't work anymore.
I get this message:
Platform error sensor.niu - Integration 'niu' not found.

I've tried to reinstall it but nothing.
This situation stops HA from restarting or updating.

Thanks
Andrea

**Comment by robbinonline** [comment]
See my pull request since version 2021.6 is for a custom component a version number required.
In the meantime to get working again change the manifest.json
and add to the bottom: "version": "0.0.1"

See also here: https://github.com/marcelwestrahome/home-assistant-niu-component/pull/11/files

**Comment by scapman** [comment]
It now works.
Thanks!

Andrea

Il giorno sab 5 giu 2021 alle ore 13:55 robbinonline <
***@***.***> ha scritto:

**Comment by marcelwestrahome** [comment]
solved
