### ISSUE TITLE
Add custom component to HACS

### ISSUE THREAD

**Issue by syssi** [marcelwestrahome/home-assistant-niu-component#22]
Brands PR: https://github.com/home-assistant/brands/pull/2646
Custom wheels PR: Not required. No third party library in use.
HACS PR: https://github.com/hacs/default/pull/998

**Comment by syssi** [comment]
@marcelwestrahome Could you add some topics to the repository? This is required to pass one of the tests here:

https://github.com/hacs/default/pull/998/checks?check_run_id=2868309482

I've attached an example:

![example](https://user-images.githubusercontent.com/2735933/122670361-01dc2f80-d1c2-11eb-9058-7b2c1f66dc38.png)

**Comment by marcelwestrahome** [comment]
done
