### ISSUE TITLE
Known bug is solved by new firmware (v3,TRA01E18)

### ISSUE THREAD

**Issue by rmettes** [marcelwestrahome/home-assistant-niu-component#28]
I saw your comment on my pull request for the niu integration in home assistant and looked into this repo. The known bug that's causing the updates to stop is fixed by Niu in the scooters firmware v3,TRA01E18. This update has to be manually installed at a authorized dealer (so no automagical OTA install). I have this version on my scooter for a while and it's stable for me :+1:

**Comment by marcelwestrahome** [comment]
thanks wil go to the dealer then :-)

**Comment by syssi** [comment]
Could somebody add a note to the README?
