### ISSUE TITLE
Timeout after 30 seconds when not being able to fetch data from NIU

### ISSUE THREAD

**Issue by larsren73** [marcelwestrahome/home-assistant-niu-component#3]
I have tested your component for NIU scooter integration and it seems to work OK, but lately I am experiencing problems with my HA instance that perhaps is due to communication locking up occasionally.
I have this example in my log:

Logginformation (WARNING)
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:545
Integration: Sensor (documentation, issues)
First occurred: 21:06:15 (3 occurrences)
Last logged: 21:08:18

Updating niu sensor took longer than the scheduled update interval 0:00:30

Does this mean that the fetching of information does not time out until 30 seconds has passed? Couldn't this potentially lock up the frontend/backend of Home Assistant?

Also I am not aware of how often the values are polled from NIU, perhaps introducing a configuration option for poll interval would be possible to implement?

**Comment by marcelwestrahome** [comment]
Hi,

disable the following sensors:

    - Distance
    - RidingTime

may be thats helps.
(these sensors are not always available on niu side...)

The 30 seconds is a HA number.

**Comment by marcelwestrahome** [comment]
solved
