### ISSUE TITLE
no location

### ISSUE THREAD

**Issue by remcopoulus** [marcelwestrahome/home-assistant-niu-component#30]
The NIU scooter is no longer showing on the map. The scooterconnected no longer has lat&long attributes. Any ideas on how ti fix this?

**Comment by syssi** [comment]
Please go to the `developer-tools/state` panel:

http://host:port/developer-tools/state

And search for "bmsId". Do you find an entity populated be a lot of attributes?

```
bmsId: BN1xxxxxxxxxxxxxxxx
latitude: xx.xxxxxxx
longitude: xx.xxxxxxx
gsm: xx
gps: xx
time: 1632928446845
range: xx
battery: xx
battery_grade: xx
centre_ctrl_batt: xx
unit_of_measurement: 
friendly_name: E-Scooter
icon: mdi:motorbike-electric
device_class: connectivity
```

This entity should be shown at the map.

**Comment by remcopoulus** [comment]
Don't see anything with mbsId. Tried reinstalling 1.0.0. via hacs, but no succes.
Do see latitude and longitude as separate sensors, but not as location.

**Comment by syssi** [comment]
Could you check your homeassistant.log? Do you see any errors?

**Comment by remcopoulus** [comment]
I had to update hass to a newer version, now its working again. Sorry to bother you
