### ISSUE TITLE
Several entities still not populating after issue #46 was fixed

### ISSUE THREAD

**Issue by Zamboniman** [marcelwestrahome/home-assistant-niu-component#52]
Some of my entities now have correct data after issue #46 was solved, however not all of them do.

The following entities continue to show 'unknown' or have meaningless data:

- [ ] 1. All of the 'last track' entities show as 'unknown', and the map does not work
- [ ] 2. Battery Charge shows as unknown, even after turning on the scooter and connecting with bluetooth to the app
- [ ] 3. Battery Grade shows as 0%. Not sure what I should be seeing there.
- [ ] 4. Centrctrlbat shows as 0%. Not sure what I should be seeing there.
- [ ] 5. HDOP (not sure what that is actually) shows as 0
- [ ] 6. Latitude and longitude show as 0
- [ ] 7. Temperature shows as 0 degrees C. That can't be right. 
- [ ] 8. TemperatureDesc (not sure what that is) shows as 'overcooled'. That doesn't seem right either
- [ ] 9. Time Left shows as 0h. However the battery is fully charged.
- [ ] 10. Times charged shows as unknown. The app shows the correct value
- [ ] 11. Some entities show '0' but I suspect it's not an issue as I would expect them to show '0' at this time, such as 'current speed'. I'll need to go for a ride to determine if that updates correctly

So it appears certain entities are still not getting data from the server correctly.

**Comment by syssi** [comment]
This is a anonymized `https://app-api-fk.niu.com/v5/scooter/motor_data/index_info?sn=...` response of your scooter:

```
{
    "data": {
        "alarm_sound_status": true,
        "back_wheel_id": "",
        "back_wheel_pressure": 0,
        "back_wheel_status": {
            "communication_failure": false,
            "connected": false,
            "leak": false,
            "paired": false,
            "power_low": false,
            "pressure_high": false,
            "pressure_low": false,
            "temperature_high": false,
            "temperature_low": false
        },
        "backend_tire_gauge_value": 0,
        "batteries": {
            "compartmentA": {
                "batteryCharging": 0,
                "bmsId": "",
                "gradeBattery": "",
                "isConnected": false
            }
        },
        "batteryDetail": true,
        "battery_cang_lock": false,
        "battery_level": 66,
        "battery_range": "",
        "centreCtrlBattery": 0,
        "charging_time": "0",
        "cycling_model": "2",
        "estimatedMileage": 43,
        "estimatedMileageRatio": 650,
        "front_wheel_id": "",
        "front_wheel_pressure": 0,
        "front_wheel_status": {
            "communication_failure": false,
            "connected": false,
            "leak": false,
            "paired": false,
            "power_low": false,
            "pressure_high": false,
            "pressure_low": false,
            "temperature_high": false,
            "temperature_low": false
        },
        "frontend_tire_gauge_value": 0,
        "gps": 0,
        "gpsTimestamp": 0,
        "gsm": 0,
        "hdop": 0,
        "infoTimestamp": 0,
        "isAccOn": 0,
        "isCharging": 0,
        "isConnected": true,
        "isFortificationOn": "0",
        "is_cushion_lock_on": false,
        "is_tire_gauge_connected": false,
        "lastTrack": {
            "distance": 9988,
            "ridingTime": 5177,
            "time": 1685306021000
        },
        "leftTime": "0",
        "locationType": 1,
        "lockStatus": 1,
        "nowSpeed": 0,
        "postion": {
            "lat": 0,
            "lng": 0
        },
        "shakingValue": 0,
        "ss_online_sta": "0",
        "ss_protocol_ver": -1,
        "time": 0
    },
    "desc": "Successful",
    "status": 0,
    "trace": "Successful"
}
```

This section is exposed by the custom component:

```
        "batteries": {
            "compartmentA": {
                "batteryCharging": 0,
                "bmsId": "",
                "gradeBattery": "",
                "isConnected": false
            }
        },
```

which isn't populated properly in your case. We should pick the `"battery_level": 66,` key instead.

**Comment by marcelwestrahome** [comment]
just to be sure,  is this a scooter or step ? because you connect via bluetooth ?. The integration is developed for scooters connected via 3/4g. I know the integration works with a step, but not for 100% and the step need to be connected to your phone.

**Comment by Zamboniman** [comment]
Ah, I see. It's a KQI 3 max scooter that connects to my phone via bluetooth. I figured each time the scooter is connected to the phone via bluetooth the app would sync with the server, which is how HA would get the data. Some data definitely seems to work this way, but the track data and other things do not.

**Comment by lichenophile** [comment]
I am looking at a KQi3 myself. 

Do you think this integration work well with the KQi3 blue-tooth communication protocol going forward?

**Comment by marcelwestrahome** [comment]
KQi3 only communicate via your phone, some of the sensor will work, but you always need to be connected via your phone

**Comment by marcelwestrahome** [comment]
Was about step
