### ISSUE TITLE
not work with China service

### ISSUE THREAD

**Issue by pervolianinen** [marcelwestrahome/home-assistant-niu-component#54]
I using niu rqi with China app/ How to connect to China services?

**Comment by marcelwestrahome** [comment]
not sure you need a different end point, but for outside china it is difficult to determ

**Comment by Mit2g** [comment]
> not sure you need a different end point, but for outside china it is difficult to determ

Yes, CN services has its independent domain. U can check [here](https://github.com/goxofy/home-assistant-niu-component/blob/master/custom_components/niu/sensor.py)
I tried to just replace sensor.py with that but fail to authenicate. If u can, plz add support for CN services and thanks

**Comment by pervolianinen** [comment]
> not sure you need a different end point, but for outside china it is difficult to determ

I'm currently using a Chinese app outside of China. Everything is working.

What you meen wen closed #48 and write "please see other thread"?

**Comment by pervolianinen** [comment]
![niu china](https://github.com/marcelwestrahome/home-assistant-niu-component/assets/74545183/383ef199-74c3-4cbc-83af-4136dd18b148)
> > not sure you need a different end point, but for outside china it is difficult to determ
> 
> Yes, CN services has its independent domain. U can check [here](https://github.com/goxofy/home-assistant-niu-component/blob/master/custom_components/niu/sensor.py) I tried to just replace sensor.py with that but fail to authenicate. If u can, plz add support for CN services and thanks

it's china domain... 
ACCOUNT_BASE_URL = "https://account.niu.com"

Page after login, above

**Comment by Mit2g** [comment]
> > not sure you need a different end point, but for outside china it is difficult to determ
> 
> I'm currently using a Chinese app outside of China. Everything is working.
> 
> What you meen wen closed #48 and write "please see other thread"?

Did u use mail as account? I am using phone number as account and met issue like u related https://github.com/marcelwestrahome/home-assistant-niu-component/issues/48. And it closed. I think u met same issue so I comment your issue below

**Comment by pervolianinen** [comment]
> Did u use mail as account?

Yes. 

I use  https://github.com/goxofy/home-assistant-niu-component/ and all work fine now.
