### ISSUE TITLE
Country Setting

### ISSUE THREAD

**Issue by codeclinic** [marcelwestrahome/home-assistant-niu-component#6]
What format does the Country setting take in the sensor setup?

Telephone Country code eg +49
International Country code eg DE
Global Country name eg Germany
or
Local Country name eg Deutschland

??

I can't get it to connect but narrowing down the correct format will at least put me one step closer.

**Comment by robbinonline** [comment]
Netherlands works fine here.

**Comment by dathosim** [comment]
the country code attempt is numeric 
https://countrycode.org/
For Germany is 49 (not +49)
For Italy is 39

**Comment by marcelwestrahome** [comment]
closed
