### ISSUE TITLE
Update the component for working with API

### ISSUE THREAD

**Issue by robbinonline** [marcelwestrahome/home-assistant-niu-component#7]
Can you update the component for working with the API instead using username/password?

https://github.com/cascha42/niu-info

**Comment by marcelwestrahome** [comment]
later, to busy with other project

**Comment by syssi** [comment]
Why do you prefer the token over username/password? The API endpoint is in both cases the same. In case of the token the auth step is skipped and the token must be extracted by MITM.

**Comment by marcelwestrahome** [comment]
reading the link you mention, it seems not easy to get the token. is the userid / password not more user friendly ?

**Comment by marcelwestrahome** [comment]
component has a new setup
